export const CARD_BG = [
    { id: 1, bgcolor: 'linear-gradient(135deg, #e6f8f3 0%, #f7fcfa 100%)'},
    { id: 2, bgcolor: 'linear-gradient(135deg, #fef9e7 0%, #fffdf4 100%)'},
    { id: 3, bgcolor: 'linear-gradient(135deg, #eaf7ff 0%, #f3fbff 100%)'},
    { id: 4, bgcolor: 'linear-gradient(135deg, #fff2e9 0%, #fff8f3-100%)'},
    { id: 5, bgcolor: 'linear-gradient(135deg, #e7f6fe 0%, #f4fafd-100%)'},
    { id: 6, bgcolor: 'linear-gradient(135deg, #f5f5f5 0%, #fbfbfb 100%)'},
    { id: 7, bgcolor: 'linear-gradient(135deg, #fff4fc 0%, #fff8fd 100%)'},
    { id: 8, bgcolor: 'linear-gradient(135deg, #e8fef3 0%, #f5fef8-100%)'},
    { id: 9, bgcolor: 'linear-gradient(135deg, #f0ecff 0%, #f7f5ff 100%)'},
    { id: 10, bgcolor: 'linear-gradient(135deg, #fef2f2 0%, #fff8f8 100%)' }
]

export const APP_FEATURES = [
    {
        id: "01",
        title: "Tailored Just for You",
        description: "Get interview questions and model answers based on your role, experience, and specific focus areas - no more generic preparation. Our AI analyzes your profile to deliver personalized content that aligns with your career goals and highlights your strengths, ensuring you're prepared for exactly what matters in your next interview."
    },
    {
        id: "02",
        title: "Learn at your own Pace",
        description: "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered explanations that adapt to your learning style. Toggle between beginner, intermediate, and expert levels to gradually build your confidence without feeling overwhelmed, making interview preparation less stressful and more effective."
    },
    {
        id: "03",
        title: "Capture Your Insight",
        description: "Add personal notes to any question and pin important ones to the top - making your learning more organized and accessible. Track your progress with confidence ratings for each answer, and receive tailored recommendations based on your strengths and areas for improvement, creating a truly personalized preparation journey."
    },
    {
        id: "04",
        title: "Understand the 'Why' Behind the Answers",
        description: "Beyond just answers - unlock detailed concept explanations generated by AI, helping you truly master each topic. See real-world applications, common pitfalls to avoid, and strategic frameworks that showcase your expertise. This deeper understanding transforms memorized answers into authentic, impressive responses that set you apart from other candidates."
    },
    {
        id: "05",
        title: "Save, Organise, and Revisit",
        description: "Easily save your interview sets, organise them in your dashboard, and pick up your preparation exactly where you left off. Set preparation milestones with our smart scheduling tool, receive timely reminders before your interview, and access your materials across all devices - ensuring you're always ready, wherever you are."
    }
]